### PR TITLE
ISSUE-06: Deep merge nested context data and trigger data.

### LINKED ISSUE #6: TrackingProvider does not deepmerge nested payload and options data.
### Expected Design / Behavior

TrackingProvides allows for nested components which merge in the data into each level. Currently the payload objects don't get deep-merged resulting in loss of top level(default) data.

Example: For a payload schema defined at the top level like
```
{
     "hello" : "world",
     "foo" : { "bar": "one" }
}
```
And Nested element like
```
{
    "something" : "new",
    "foo" : {"bar": "two",  "car" : "two" }
}
```
Should result in
```
{
    "hello" : "world",
    "something" : "new",
    "foo" : { "bar": "two" , "car" : "two" }
}
```

Nested elements are going to provide more accurate details than the top level components which will provide default data. Hence the preference should be given to nested data.

Similar behavior is also expected from `TrackingTrigger` nested within `TrackingProvider` so that the data from `TrackingTrigger` is given priority and it deep merges with the data from `TrackingProvider`

A real example of this can be the root `<App />` component wrapped with `<TrackingProvider payload={defaultData}/>` and individual App Pages overwrite the `pageName` in payload Object where the attribute `pageName` is nested in the payload schema.

### Actual Design / Behavior

Currently as per the above example this will result in

```
{
    "hello" : "world",
    "something" : "new",
    "foo" : { "bar": "one"  }
}
```

### Steps to Reproduce, if applicable

1. Create a root `<TrackingProvider payload={defaultPayload}/>` with default payload which has nested objects in payload
2. Create a child `<TrackingProvider payload={nestedPayload}/>` which overwrites nested objects from default payload
3. Trigger an event and see the payload it was triggered with.

### Possible Solutions
Update [mergeContextData](https://github.com/ExpediaGroup/react-event-tracking/blob/master/src/components/TrackingProvider/TrackingProvider.js#L73) function to support the above usecase

Use DeepMerge [here](https://github.com/ExpediaGroup/react-event-tracking/blob/master/src/components/TrackingProvider/TrackingProvider.js#L127-L137) to support deepmerging of data passed into TrackingTrigger

### Your Environment

* Version of component: 1.2.0
* Browser name and version: Chrome  89.0.4389.114 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by yateenkedare**
### GITHUB ISSUE

Fixes #6 

### Description

Updates context data merge to support deep merge so that data is not lost from attributes of type objects

### How to Test

(See included unit test)
Create Nested `TrackingProviders` with a `TrackingTrigger` to trigger an event. Set payload/options and event payload/options at every level of `TrackingProvider`.  Also send payload/options in `TrackingTrigger`.
Ensure that all the data is merged in correctly before the event is triggered

### PR Author Checklist

- [x] GitHub ISSUE LINKED
- [x] Github Issue number & title in PR title (`ISSUE-XXXX: Ticket title`)
- [x] Cross Browser tested if necessary
- [x] Unit tests written (if necessary) and `npm test` passing locally
- [x] Unit test coverage not decreased for any touched files
- [x] Conflicts resolved
- [ ] PR Assigned to code reviewer

### Reviewer Checklist

- [ ] Tested locally
- [ ] Validated against ISSUE description
- [ ] Verified author checklist
- [ ] CI build/test passed and reported back green.

### CODE REVIEW

File: src/components/TrackingProvider/TrackingProvider.js [hunk 1]
```diff
@@ -16,6 +16,7 @@
 import React, {PureComponent} from 'react';
 import PropTypes from 'prop-types';
 import TrackingContext from '../../context/TrackingContext';
+const merge = require('merge-deep');
```
Comment (underbyte) [inline src/components/TrackingProvider/TrackingProvider.js]: We're trying to keep this module dependency free that can run on both server and client. Probably thing to do here is to write a small deep merge function.

Comment (yateenkedare) [reply src/components/TrackingProvider/TrackingProvider.js]: Got it!
Ideally, a good deep merge function typically covers cases such that Object, Arrays and other primitive and non-primitive data types and should merge recursively. It should also be able to handle changes in data type where obj 1 sends the data of type 1 and obj 2 sends data of type 2 and possibly handle many other cases. 

The purpose we're trying to achieve is only with Object & String types and only extends to 3 levels deep right now. 

So the question is, What all cases should this merge module cover?

**Review by underbyte — APPROVED** [review]
